version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: secops
      POSTGRES_PASSWORD: secops
      POSTGRES_DB: secops
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/test
    ports: ["7474:7474", "7687:7687"]
  victoriametrics:
    image: victoriametrics/victoria-metrics
    ports: ["8428:8428"]
  kafka:
    image: bitnami/kafka:3.7
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports: ["9092:9092"]
    depends_on: ["zookeeper"]
  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports: ["2181:2181"]
